id: P55543513
initial_creation_type: ocr
source_metadata:
  volumes:
    83bd14958d744408bc0cce6a0b71b9bc:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: རྗེ་བཙུན་འཕགས་པ་འཇམ་དཔལ་གྱི་སྙིང་རྗེ་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
